// Generated by PTA Compiler - Safety-Stripped ARM64 Assembly
// Optimized for Snapdragon 8 Gen 4 Oryon Cores

.global pta_process_image
.text
.align 2

pta_process_image:
    // Function prologue
    stp x29, x30, [sp, #-16]!
    mov x29, sp

    // Save callee-saved registers
    stp x19, x20, [sp, #-16]!
    stp x21, x22, [sp, #-16]!













mov w10, w0

mov w11, w1

mov x6, x2

mov x7, x3




LOOP_START:


ldr s8, [x6]



// w4 now contains the dynamic brightness value passed from JNI
    dup v31.8b, w4
    uqadd v9.8b, v8.8b, v31.8b



// Safety-stripped: CMP
// Safety-stripped: %r6
// Safety-stripped: #255

// Safety-stripped: MOV_IF_GT
// Safety-stripped: %r6
// Safety-stripped: #255



str s9, [x7]



add x6, x6, 4

add x7, x7, 4



sub w10, w10, 1

cmp w10, 0

b.gt LOOP_START



mov w10, w0

sub w11, w11, 1

cmp w11, 0

b.gt LOOP_START



b exit_pta_process_image

exit_pta_process_image:
    // Restore callee-saved registers
    ldp x21, x22, [sp], #16
    ldp x19, x20, [sp], #16

    // Function epilogue
    ldp x29, x30, [sp], #16
    ret

