import os
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

def set_default_style(doc):
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Times New Roman'
    font.size = Pt(12)
    # Ensure East Asian fonts also Times New Roman
    font.element.rPr.rFonts.set(qn('w:eastAsia'), 'Times New Roman')
    font.element.rPr.rFonts.set(qn('w:cs'), 'Times New Roman')
    style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY

def add_heading(doc, text, level, size_pt):
    heading = doc.add_heading(text, level=level)
    heading_style = heading.style
    heading_style.font.name = 'Times New Roman'
    heading_style.font.size = Pt(size_pt)
    heading.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    return heading

def add_toc(doc):
    # Insert a Table of Contents field
    paragraph = doc.add_paragraph()
    run = paragraph.add_run()
    fldChar1 = OxmlElement('w:fldChar')
    fldChar1.set(qn('w:fldCharType'), 'begin')
    instrText = OxmlElement('w:instrText')
    instrText.text = 'TOC \\o "1-3" \\h \\z \\u'
    fldChar2 = OxmlElement('w:fldChar')
    fldChar2.set(qn('w:fldCharType'), 'separate')
    fldChar3 = OxmlElement('w:fldChar')
    fldChar3.set(qn('w:fldCharType'), 'end')
    run._r.append(fldChar1)
    run._r.append(instrText)
    run._r.append(fldChar2)
    run._r.append(fldChar3)
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER


def add_section(doc, title, level, size_pt, content_lines=None):
    add_heading(doc, title, level, size_pt)
    if content_lines:
        for line in content_lines:
            p = doc.add_paragraph(line)
            p.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
            p.runs[0].font.name = 'Times New Roman'
            p.runs[0].font.size = Pt(12)


def main():
    doc = Document()
    set_default_style(doc)
    # Title page (optional)
    doc.add_paragraph('')
    # Table of Contents placeholder
    add_toc(doc)
    doc.add_page_break()

    # Sections 5 (Abstract etc.)
    abstract_heading = add_heading(doc, '5. Abstract', level=1, size_pt=16)
    # Placeholder for abstract content
    doc.add_paragraph('Provide abstract here.', style='Normal')
    doc.add_paragraph('Problem overview', style='Normal')
    doc.add_paragraph('Solution approach', style='Normal')
    doc.add_paragraph('Key features/system', style='Normal')
    doc.add_paragraph('Technologies used', style='Normal')
    doc.add_paragraph('Outcome/impact', style='Normal')
    doc.add_page_break()

    # Table of Contents section (6.)
    add_heading(doc, '6. Table of Contents', level=1, size_pt=16)
    doc.add_paragraph('Chapters + subtopics with page numbers will be generated by the TOC field.', style='Normal')
    doc.add_page_break()

    # MAIN BODY sections
    add_heading(doc, 'MAIN BODY', level=1, size_pt=16)
    # Chapter 1
    add_heading(doc, 'Chapter 1: Introduction', level=2, size_pt=14)
    add_section(doc, '1.1 Introduction', level=3, size_pt=12)
    add_section(doc, '1.2 Background / Motivation', level=3, size_pt=12)
    add_section(doc, '1.3 Problem Statement', level=3, size_pt=12)
    add_section(doc, '1.4 Objectives & Methodology', level=3, size_pt=12)
    add_section(doc, '1.5 Project Organization', level=3, size_pt=12)
    doc.add_page_break()

    # Chapter 2
    add_heading(doc, 'Chapter 2: Proposed System', level=2, size_pt=14)
    add_section(doc, '2.1 System Overview', level=3, size_pt=12)
    add_section(doc, '2.2 System Workflow / Interaction Flow', level=3, size_pt=12)
    add_section(doc, '2.3 Key Features / Innovations', level=3, size_pt=12)
    doc.add_page_break()

    # Chapter 3
    add_heading(doc, 'Chapter 3: Hardware & Software Requirements', level=2, size_pt=14)
    add_section(doc, '3.1 Software Requirements', level=3, size_pt=12)
    add_section(doc, '3.2 Hardware Requirements', level=3, size_pt=12)
    add_section(doc, '3.3 Security / Reliability (optional but strong addition)', level=3, size_pt=12)
    doc.add_page_break()

    # Chapter 4
    add_heading(doc, 'Chapter 4: System Architecture', level=2, size_pt=14)
    add_section(doc, '4.1 High-Level Architecture', level=3, size_pt=12)
    add_section(doc, '4.2 Data Flow / Diagrams', level=3, size_pt=12)
    doc.add_page_break()

    # Chapter 5
    add_heading(doc, 'Chapter 5: System Design / Modules', level=2, size_pt=14)
    doc.add_paragraph('Module-wise breakdown', style='Normal')
    doc.add_paragraph('Each module includes:', style='Normal')
    doc.add_paragraph('Responsibility', style='Normal')
    doc.add_paragraph('Design', style='Normal')
    doc.add_paragraph('Implementation', style='Normal')
    doc.add_paragraph('Output', style='Normal')
    doc.add_page_break()

    # Chapter 6
    add_heading(doc, 'Chapter 6: Team Contribution', level=2, size_pt=14)
    add_section(doc, 'Member-wise responsibilities', level=3, size_pt=12)
    add_section(doc, 'Work distribution', level=3, size_pt=12)
    add_section(doc, 'Integration flow', level=3, size_pt=12)
    doc.add_page_break()

    # Chapter 7
    add_heading(doc, 'Chapter 7: Limitations', level=2, size_pt=14)
    add_section(doc, 'Current constraints', level=3, size_pt=12)
    add_section(doc, 'Missing features', level=3, size_pt=12)
    add_section(doc, 'Technical boundaries', level=3, size_pt=12)
    doc.add_page_break()

    # Chapter 8
    add_heading(doc, 'Chapter 8: Enhancements / Future Work', level=2, size_pt=14)
    add_section(doc, 'Improvements', level=3, size_pt=12)
    add_section(doc, 'Scalability ideas', level=3, size_pt=12)
    add_section(doc, 'Advanced features', level=3, size_pt=12)
    doc.add_page_break()

    # Chapter 9
    add_heading(doc, 'Chapter 9: Conclusion', level=2, size_pt=14)
    add_section(doc, 'Summary of work', level=3, size_pt=12)
    add_section(doc, 'Achievements', level=3, size_pt=12)
    add_section(doc, 'Real-world impact', level=3, size_pt=12)
    doc.add_page_break()

    # References
    add_heading(doc, 'References', level=1, size_pt=16)
    doc.add_paragraph('Books', style='Normal')
    doc.add_paragraph('Research papers', style='Normal')
    doc.add_paragraph('Tools / documentation', style='Normal')

    output_path = os.path.join(os.getcwd(), 'pk.docx')
    doc.save(output_path)
    print(f'Document generated at {output_path}')

if __name__ == '__main__':
    main()
