#include "emitter.h"
#include <iostream>
#include <sstream>

using namespace std;

Emitter::Emitter(const string& outputFilename)
    : filename_(outputFilename), indent_level_(0) {
    output_file_.open(outputFilename);
    if (!output_file_.is_open()) {
        throw runtime_error("Failed to open output file: " + outputFilename);
    }
}

bool Emitter::emitAssembly(const vector<Token>& tokens, Mapper& mapper) {
    try {
        writeHeader();

        // Process tokens and generate assembly
        for (size_t i = 0; i < tokens.size(); ++i) {
            const Token& token = tokens[i];

            switch (token.type) {
                case TokenType::COMMENT:
                    writeComment(token.value);
                    break;

                case TokenType::LABEL:
                    writeLabel(token.value.substr(0, token.value.size() - 1)); // Remove colon
                    break;

                case TokenType::NEWLINE:
                    output_file_ << endl;
                    break;

                case TokenType::LOAD:
                case TokenType::STORE:
                case TokenType::ADD:
                case TokenType::SUB:
                case TokenType::CMP:
                case TokenType::MOV_IF_GT:
                case TokenType::JMP_GT:
                case TokenType::RET:
                    // Handle instructions - collect operands
                    {
                        vector<string> operands;
                        size_t j = i + 1;

                        // Collect operands until next instruction, newline, or end
                        while (j < tokens.size()) {
                            TokenType type = tokens[j].type;
                            if (type == TokenType::NEWLINE || type == TokenType::COMMENT || 
                                type == TokenType::LABEL || type == TokenType::END_OF_FILE ||
                                type == TokenType::LOAD || type == TokenType::STORE ||
                                type == TokenType::ADD || type == TokenType::SUB ||
                                type == TokenType::CMP || type == TokenType::MOV_IF_GT ||
                                type == TokenType::JMP_GT || type == TokenType::RET) {
                                break;
                            }

                            if (type == TokenType::REGISTER ||
                                type == TokenType::VARIABLE ||
                                type == TokenType::IMMEDIATE ||
                                type == TokenType::MEMORY_REF ||
                                type == TokenType::IDENTIFIER) {
                                operands.push_back(tokens[j].value);
                            }
                            j++;
                        }

                        try {
                            // Debug logging
                            // cerr << "Instruction: " << token.value << " (line " << token.line << ") Operands: " << operands.size() << endl;
                            // for (const auto& op : operands) cerr << "  Op: " << op << endl;

                            string asm_instr = mapper.mapInstruction(token.type, operands);
                            writeInstruction(asm_instr);
                        } catch (const exception& e) {
                            cerr << "Warning: " << e.what() << " at line " << token.line << " (found " << operands.size() << " operands)" << endl;
                            for (size_t k = 0; k < operands.size(); ++k) {
                                cerr << "  operand[" << k << "]: " << operands[k] << endl;
                            }
                        }
                    }
                    break;

                default:
                    // Skip other token types
                    break;
            }
        }

        writeFooter();
        return true;

    } catch (const exception& e) {
        cerr << "Error generating assembly: " << e.what() << endl;
        return false;
    }
}

void Emitter::writeHeader() {
    output_file_ << "// Generated by PTA Compiler - Safety-Stripped ARM64 Assembly" << endl;
    output_file_ << "// Optimized for Snapdragon 8 Gen 4 Oryon Cores" << endl;
    output_file_ << endl;
    output_file_ << ".global pta_process_image" << endl;
    output_file_ << ".text" << endl;
    output_file_ << ".align 2" << endl;
    output_file_ << endl;
    output_file_ << "pta_process_image:" << endl;
    output_file_ << "    // Function prologue" << endl;
    output_file_ << "    stp x29, x30, [sp, #-16]!" << endl;
    output_file_ << "    mov x29, sp" << endl;
    output_file_ << endl;

    // Save callee-saved registers if needed
    output_file_ << "    // Save callee-saved registers" << endl;
    output_file_ << "    stp x19, x20, [sp, #-16]!" << endl;
    output_file_ << "    stp x21, x22, [sp, #-16]!" << endl;
    output_file_ << endl;
}

void Emitter::writeFooter() {
    output_file_ << endl << "exit_pta_process_image:" << endl;
    output_file_ << "    // Restore callee-saved registers" << endl;
    output_file_ << "    ldp x21, x22, [sp], #16" << endl;
    output_file_ << "    ldp x19, x20, [sp], #16" << endl;
    output_file_ << endl;
    output_file_ << "    // Function epilogue" << endl;
    output_file_ << "    ldp x29, x30, [sp], #16" << endl;
    output_file_ << "    ret" << endl;
    output_file_ << endl;
}

void Emitter::writeInstruction(const string& instruction) {
    output_file_ << getIndent() << instruction << endl;
}

void Emitter::writeLabel(const string& label) {
    output_file_ << endl << label << ":" << endl;
}

void Emitter::writeComment(const string& comment) {
    output_file_ << getIndent() << "// " << comment << endl;
}

void Emitter::close() {
    if (output_file_.is_open()) {
        output_file_.close();
    }
}

string Emitter::getIndent() const {
    return string(indent_level_ * 4, ' ');
}